### ISSUE TITLE
"Failed to setup" Error

### ISSUE THREAD

**Issue by gregorymartin** [BeryJu/hass-ticktick#64]
I've been getting a "Failed to setup" error with this integration for a while now:

<img width="267" alt="Screen Shot 2021-06-22 at 5 20 09 PM" src="https://user-images.githubusercontent.com/1591110/123015866-3694e600-d37e-11eb-8c22-81abda31ad3e.png">

When I check the logs, here's what I get which appears to be some sort of I/O error:

```
Logger: homeassistant.config_entries
Source: util/async_.py:140
First occurred: 10:14:34 AM (1 occurrences)
Last logged: 10:14:34 AM

Error setting up entry TickTick for ticktick
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ticktick/__init__.py", line 62, in async_setup_entry
    client.login(entry.data.get("username"), entry.data.get("password"))
  File "/config/custom_components/ticktick/api.py", line 21, in login
    resp = self._session.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/ticktick/api.py, line 21: resp = self._session.post(
```

**Comment by pcon** [comment]
I am also getting the same error when I try to login.

**Comment by BeryJu** [comment]
Yeah I'm actually getting the same error, just haven't gotten around to debugging what hass changed now

**Comment by pcon** [comment]
Works for me now.  Thanks!
