### ISSUE TITLE
Setting a due_date with a + does not work

### ISSUE THREAD

**Issue by pcon** [BeryJu/hass-ticktick#65]
It appears that the value pulled from `call.data.get("due_date", "")` is coming back as an `int` and therefore the `startswith` method does not exist.

```
[2797517984] Error handling message: Unknown error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1216, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 350, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ticktick/__init__.py", line 26, in handler
    if due_date_raw.startswith("+"):
AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by BeryJu** [comment]
In retrospective, choosing + as a prefix was maybe not the best idea, it works if you do 

```yaml
due_date: '+3'
```

but thats not ideal

**Comment by BeryJu** [comment]
I'm gonna add support for using `123m` for relative delta in minutes

**Comment by BeryJu** [comment]
closed by https://github.com/BeryJu/hass-ticktick/commit/ebeb6fd7d98878a7af9060e36f1e19f291489844
